'use client';

import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { CalendarDays, AlertCircle, CheckCircle } from 'lucide-react';
import { getMembersListStrict } from '@/lib/dashboardApi';
import { getIncomeCategoriesStrict } from '@/lib/treasuryApi';
import { submitTreasuryIncomeRecord } from '@/services/recordIncomeSubmit';
import type { IncomeRecord } from '@/components/treasurydashboard/recordIncome/IncomeReceipt';

const formSchema = z.object({
  date: z.string().min(1, 'Date is required'),
  incomeType: z.string().min(1, 'Income type is required'),
  memberId: z.string().min(1, 'Member selection is required'),
  amount: z.string().min(1, 'Amount is required'),
  paymentMethod: z.string().min(1, 'Payment method is required'),
  paymentDetail: z.string().optional(),
});

type FormValues = z.infer<typeof formSchema>;

interface Member {
  id: string;
  first_name: string;
  last_name: string;
}

interface IncomeCategory {
  id: string;
  name: string;
}

export interface RecordIncomeModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: (receiptNumber: string) => void;
}

export function RecordIncomeModal({ open, onOpenChange, onSuccess }: RecordIncomeModalProps) {
  const [members, setMembers] = useState<Member[]>([]);
  const [categories, setCategories] = useState<IncomeCategory[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      date: new Date().toISOString().split('T')[0],
      incomeType: '',
      memberId: '',
      amount: '',
      paymentMethod: 'cash',
      paymentDetail: '',
    },
  });

  // Fetch members and income categories when modal opens
  useEffect(() => {
    if (!open) {
      return;
    }

    const fetchData = async () => {
      setIsLoading(true);
      setError(null);
      try {
        const [membersList, categoriesList] = await Promise.all([
          getMembersListStrict(250),
          getIncomeCategoriesStrict(),
        ]);

        setMembers(
          membersList.map((m) => ({
            id: m.id,
            first_name: m.first_name,
            last_name: m.last_name,
          }))
        );

        setCategories(
          categoriesList.map((c) => ({
            id: c.id,
            name: c.name,
          }))
        );
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load members and categories');
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, [open]);

  const onSubmit = async (data: FormValues) => {
    setIsSubmitting(true);
    setError(null);
    setSuccess(null);

    try {
      const member = members.find((m) => m.id === data.memberId);
      const memberName = member ? `${member.first_name} ${member.last_name}`.trim() : 'Anonymous';

      // Convert ISO date to DD/MM/YYYY format for the service
      const dateParts = data.date.split('-');
      const ddmmyyyy = `${dateParts[2]}/${dateParts[1]}/${dateParts[0]}`;

      const incomeRecord: IncomeRecord = {
        id: '', // Will be set by server
        date: ddmmyyyy,
        incomeType: data.incomeType,
        memberId: data.memberId,
        memberName,
        amount: Number(data.amount),
        currency: 'GHS',
        paymentMethod: data.paymentMethod,
        paymentDetail: data.paymentDetail,
        receiptNumber: '', // Will be generated by server
        notification: [],
        recordedAt: new Date().toISOString(),
        recordedBy: '', // Will be set by backend
      };

      const result = await submitTreasuryIncomeRecord(incomeRecord);
      setSuccess(`Income recorded successfully! Receipt #${result.receipt_number}`);
      onSuccess?.(result.receipt_number);

      // Reset form and close modal after 2 seconds
      setTimeout(() => {
        form.reset({
          date: new Date().toISOString().split('T')[0],
          incomeType: '',
          memberId: '',
          amount: '',
          paymentMethod: 'cash',
          paymentDetail: '',
        });
        onOpenChange(false);
        setSuccess(null);
      }, 2000);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to record income');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancel = () => {
    setError(null);
    setSuccess(null);
    form.reset({
      date: new Date().toISOString().split('T')[0],
      incomeType: '',
      memberId: '',
      amount: '',
      paymentMethod: 'cash',
      paymentDetail: '',
    });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogTitle className="hidden">Record Income</DialogTitle>
      <DialogContent
        showCloseButton={false}
        className="sm:max-w-[500px] p-0 overflow-hidden border-none shadow-2xl rounded-[1rem] bg-card"
      >
        <div className="flex flex-col text-[#0f2846]">
          {/* Header */}
          <div className="px-8 pt-8 pb-4 text-center sm:text-left flex flex-col items-center">
            <h2 className="text-[22px] font-bold tracking-tight text-[#0f2846]">Record Income</h2>
            <p className="text-[13px] text-slate-500 mt-1">
              Create, submit and print your individual or department records
            </p>
          </div>

          {/* Success Message */}
          {success && (
            <div className="px-8 pt-4">
              <div className="flex items-center gap-3 rounded-lg bg-green-50 border border-green-200 p-3">
                <CheckCircle className="h-5 w-5 text-green-600 flex-shrink-0" />
                <span className="text-sm text-green-800">{success}</span>
              </div>
            </div>
          )}

          {/* Error Message */}
          {error && (
            <div className="px-8 pt-4">
              <div className="flex items-center gap-3 rounded-lg bg-red-50 border border-red-200 p-3">
                <AlertCircle className="h-5 w-5 text-red-600 flex-shrink-0" />
                <span className="text-sm text-red-800">{error}</span>
              </div>
            </div>
          )}

          {/* Form Content */}
          <div className="px-8 pb-8 max-h-[75vh] overflow-y-auto custom-scrollbar">
            {isLoading ? (
              <div className="flex items-center justify-center py-8">
                <div className="text-center">
                  <div className="h-8 w-8 rounded-full border-2 border-slate-300 border-t-[#28c1a6] animate-spin mx-auto mb-3"></div>
                  <p className="text-sm text-slate-500">Loading members and categories...</p>
                </div>
              </div>
            ) : (
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                  <FormField
                    control={form.control}
                    name="date"
                    render={({ field }) => (
                      <FormItem className="space-y-1.5">
                        <FormLabel className="flex text-[14px] font-medium text-[#1c385c]">
                          Date <span className="text-red-500 ml-1">*</span>
                        </FormLabel>
                        <FormControl>
                          <div className="relative">
                            <Input
                              type="date"
                              className="bg-transparent border-slate-200 rounded-[8px] h-11 text-[14px] pl-4 pr-11 focus-visible:ring-1 focus-visible:ring-[#28c1a6] focus-visible:border-[#28c1a6] [&::-webkit-calendar-picker-indicator]:opacity-0 [&::-webkit-calendar-picker-indicator]:absolute [&::-webkit-calendar-picker-indicator]:right-0 [&::-webkit-calendar-picker-indicator]:w-10 [&::-webkit-calendar-picker-indicator]:h-full [&::-webkit-calendar-picker-indicator]:cursor-pointer"
                              disabled={isSubmitting}
                              {...field}
                            />
                            <div className="absolute inset-y-0 right-0 pr-3.5 flex items-center pointer-events-none text-[#0f2846]">
                              <CalendarDays className="h-5 w-5" strokeWidth={1.5} />
                            </div>
                          </div>
                        </FormControl>
                        <FormMessage className="text-[12px]" />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="incomeType"
                    render={({ field }) => (
                      <FormItem className="space-y-1.5">
                        <FormLabel className="flex text-[14px] font-medium text-[#1c385c]">
                          Income Type <span className="text-red-500 ml-1">*</span>
                        </FormLabel>
                        <Select
                          onValueChange={field.onChange}
                          defaultValue={field.value}
                          disabled={isSubmitting}
                        >
                          <FormControl>
                            <SelectTrigger className="bg-transparent border-slate-200 rounded-[8px] h-11 text-[14px] focus:ring-1 focus:ring-[#28c1a6] focus:border-[#28c1a6]">
                              <SelectValue placeholder="Select Income Type" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {categories.map((cat) => (
                              <SelectItem key={cat.id} value={cat.id}>
                                {cat.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage className="text-[12px]" />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="memberId"
                    render={({ field }) => (
                      <FormItem className="space-y-1.5">
                        <FormLabel className="flex text-[14px] font-medium text-[#1c385c]">
                          Member <span className="text-red-500 ml-1">*</span>
                        </FormLabel>
                        <Select
                          onValueChange={field.onChange}
                          defaultValue={field.value}
                          disabled={isSubmitting}
                        >
                          <FormControl>
                            <SelectTrigger className="bg-transparent border-slate-200 rounded-[8px] h-11 text-[14px] focus:ring-1 focus:ring-[#28c1a6] focus:border-[#28c1a6]">
                              <SelectValue placeholder="Search or select member" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="anonymous">Anonymous</SelectItem>
                            {members.map((member) => (
                              <SelectItem key={member.id} value={member.id}>
                                {member.first_name} {member.last_name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage className="text-[12px]" />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="amount"
                    render={({ field }) => (
                      <FormItem className="space-y-1.5">
                        <FormLabel className="flex text-[14px] font-medium text-[#1c385c]">
                          Amount <span className="text-red-500 ml-1">*</span>
                        </FormLabel>
                        <FormControl>
                          <Input
                            type="number"
                            step="0.01"
                            min="0"
                            placeholder="0.00"
                            className="bg-transparent border-slate-200 rounded-[8px] h-11 text-[14px] focus-visible:ring-1 focus-visible:ring-[#28c1a6] focus-visible:border-[#28c1a6]"
                            disabled={isSubmitting}
                            {...field}
                          />
                        </FormControl>
                        <FormMessage className="text-[12px]" />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="paymentMethod"
                    render={({ field }) => (
                      <FormItem className="space-y-1.5">
                        <FormLabel className="flex text-[14px] font-medium text-[#1c385c]">
                          Payment Method <span className="text-red-500 ml-1">*</span>
                        </FormLabel>
                        <Select
                          onValueChange={field.onChange}
                          defaultValue={field.value}
                          disabled={isSubmitting}
                        >
                          <FormControl>
                            <SelectTrigger className="bg-transparent border-slate-200 rounded-[8px] h-11 text-[14px] focus:ring-1 focus:ring-[#28c1a6] focus:border-[#28c1a6]">
                              <SelectValue placeholder="Cash" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="cash">Cash</SelectItem>
                            <SelectItem value="momo">Mobile Money</SelectItem>
                            <SelectItem value="bank_transfer">Bank Transfer</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage className="text-[12px]" />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="paymentDetail"
                    render={({ field }) => (
                      <FormItem className="space-y-1.5 pt-1">
                        <FormLabel className="flex text-[14px] font-medium text-[#1c385c]">
                          Payment Details (Optional)
                        </FormLabel>
                        <FormControl>
                          <Input
                            type="text"
                            placeholder="e.g., Transaction ID, Cheque Number"
                            className="bg-transparent border-slate-200 rounded-[8px] h-11 text-[14px] focus-visible:ring-1 focus-visible:ring-[#28c1a6] focus-visible:border-[#28c1a6]"
                            disabled={isSubmitting}
                            {...field}
                          />
                        </FormControl>
                        <FormMessage className="text-[12px]" />
                      </FormItem>
                    )}
                  />

                  <div className="flex justify-center sm:justify-center gap-4 pt-6 pb-2">
                    <Button
                      type="button"
                      variant="ghost"
                      onClick={handleCancel}
                      disabled={isSubmitting}
                      className="bg-[#bccucf] text-[#0f2846] hover:bg-[#b0bdc2] font-semibold text-[15px] h-12 px-8 rounded-[8px] min-w-[130px] bg-[#b9cfcc]"
                    >
                      Cancel
                    </Button>
                    <Button
                      type="submit"
                      disabled={isSubmitting}
                      className="bg-[#28c1a6] text-white hover:bg-[#22a68e] font-semibold text-[15px] h-12 px-8 rounded-[8px] min-w-[200px] disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {isSubmitting ? 'Recording...' : 'Record & Print Receipt'}
                    </Button>
                  </div>
                </form>
              </Form>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
