import { MemberContribution } from '@/types/memberFinance';

// API integration point: replace this with actual API call
// e.g. const members = await getMemberContributions({ page, pageSize, search })
export const MOCK_MEMBER_CONTRIBUTIONS: MemberContribution[] = [
  'Owusu William',
  'David Wilson',
  'Jonas Lantam Gbati',
  'Ama Mensah',
  'Kwame Asante',
  'Efua Owusu',
  'Kofi Darko',
  'Adwoa Sarpong',
  'Nana Agyei',
  'Akua Frimpong',
  'Kwesi Appiah',
  'Abena Nyarko',
  'Yaw Boateng',
  'Serwa Amponsah',
  'Kojo Attah',
  'Adjoa Kusi',
  'Fiifi Mensah',
  'Maame Serwaa',
  'Nii Armah',
  'Akosua Boadi',
  'Kofi Mensah',
  'Esi Amoah',
  'Kwabena Osei',
  'Abena Asante',
  'Yaa Darko',
  'Nana Boateng',
  'Kweku Frimpong',
  'Ama Nyarko',
  'Kojo Appiah',
  'Adwoa Sarpong',
  'Kwame Owusu',
  'Efua Wilson',
  'Nii Osei',
  'Akua Mensah',
  'Kofi Amoah',
  'Esi Asante',
  'Kwabena Boateng',
  'Abena Frimpong',
  'Yaw Nyarko',
  'Nana Appiah',
  'Kweku Sarpong',
  'Ama Owusu',
  'Kojo Wilson',
  'Adwoa Osei',
  'Kwame Mensah',
  'Efua Amoah',
  'Nii Asante',
  'Akua Boateng',
  'Kofi Frimpong',
  'Esi Nyarko',
  'Kwabena Appiah',
].map((name, i) => ({
  id: `m${i + 1}`,
  name,
  memberId: `SDA2026-${String(i + 1).padStart(3, '0')}`,
  phone: '+233596038258',
  avatarUrl: undefined,
  totalYTD: 3500,
  status: i % 7 === 0 ? 'Inactive' : 'Active',
  memberSince: 'Feb 12, 2022',
  titheYTD: 2800,
  offeringsYTD: 950,
  projectsYTD: 600,
  transactions: [
    { id: `t${i}1`, type: 'Tithe', date: '2024-08-10', receiptNumber: 'RCP-001', amount: 450 },
    { id: `t${i}2`, type: 'Offering', date: '2024-08-03', receiptNumber: 'RCP-002', amount: 120 },
    { id: `t${i}3`, type: 'Project', date: '2024-07-20', receiptNumber: 'RCP-004', amount: 200 },
  ],
}));
