import { Member, Message } from '@/components/departments/MessageMembers/utils/message';

export const mockMembers: Member[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '+1 (555) 123-4567',
    department: 'Youth Ministry',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    phone: '+1 (555) 234-5678',
    department: 'Youth Ministry',
  },
  {
    id: '3',
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    phone: '+1 (555) 345-6789',
    department: 'Youth Ministry',
  },
  {
    id: '4',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phone: '+1 (555) 456-7890',
    department: 'Youth Ministry',
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    phone: '+1 (555) 567-8901',
    department: 'Youth Ministry',
  },
  {
    id: '6',
    name: 'Jessica Martinez',
    email: 'jessica.martinez@example.com',
    phone: '+1 (555) 678-9012',
    department: 'Youth Ministry',
  },
  {
    id: '7',
    name: 'James Anderson',
    email: 'james.anderson@example.com',
    phone: '+1 (555) 789-0123',
    department: 'Youth Ministry',
  },
  {
    id: '8',
    name: 'Lisa Taylor',
    email: 'lisa.taylor@example.com',
    phone: '+1 (555) 890-1234',
    department: 'Youth Ministry',
  },
  {
    id: '9',
    name: 'Robert Thomas',
    email: 'robert.thomas@example.com',
    phone: '+1 (555) 901-2345',
    department: 'Youth Ministry',
  },
  {
    id: '10',
    name: 'Jennifer Moore',
    email: 'jennifer.moore@example.com',
    phone: '+1 (555) 012-3456',
    department: 'Youth Ministry',
  },
  {
    id: '11',
    name: 'William Jackson',
    email: 'william.jackson@example.com',
    phone: '+1 (555) 123-4568',
    department: 'Youth Ministry',
  },
  {
    id: '12',
    name: 'Amanda White',
    email: 'amanda.white@example.com',
    phone: '+1 (555) 234-5679',
    department: 'Youth Ministry',
  },
  {
    id: '13',
    name: 'Christopher Harris',
    email: 'christopher.harris@example.com',
    phone: '+1 (555) 345-6780',
    department: 'Youth Ministry',
  },
  {
    id: '14',
    name: 'Michelle Martin',
    email: 'michelle.martin@example.com',
    phone: '+1 (555) 456-7891',
    department: 'Youth Ministry',
  },
  {
    id: '15',
    name: 'Matthew Thompson',
    email: 'matthew.thompson@example.com',
    phone: '+1 (555) 567-8902',
    department: 'Youth Ministry',
  },
  {
    id: '16',
    name: 'Ashley Garcia',
    email: 'ashley.garcia@example.com',
    phone: '+1 (555) 678-9013',
    department: 'Youth Ministry',
  },
  {
    id: '17',
    name: 'Daniel Martinez',
    email: 'daniel.martinez@example.com',
    phone: '+1 (555) 789-0124',
    department: 'Youth Ministry',
  },
  {
    id: '18',
    name: 'Elizabeth Robinson',
    email: 'elizabeth.robinson@example.com',
    phone: '+1 (555) 890-1235',
    department: 'Youth Ministry',
  },
  {
    id: '19',
    name: 'Joshua Clark',
    email: 'joshua.clark@example.com',
    phone: '+1 (555) 901-2346',
    department: 'Youth Ministry',
  },
  {
    id: '20',
    name: 'Stephanie Rodriguez',
    email: 'stephanie.rodriguez@example.com',
    phone: '+1 (555) 012-3457',
    department: 'Youth Ministry',
  },
  {
    id: '21',
    name: 'Andrew Lewis',
    email: 'andrew.lewis@example.com',
    phone: '+1 (555) 123-4569',
    department: 'Youth Ministry',
  },
  {
    id: '22',
    name: 'Nicole Lee',
    email: 'nicole.lee@example.com',
    phone: '+1 (555) 234-5680',
    department: 'Youth Ministry',
  },
  {
    id: '23',
    name: 'Ryan Walker',
    email: 'ryan.walker@example.com',
    phone: '+1 (555) 345-6781',
    department: 'Youth Ministry',
  },
  {
    id: '24',
    name: 'Brittany Hall',
    email: 'brittany.hall@example.com',
    phone: '+1 (555) 456-7892',
    department: 'Youth Ministry',
  },
  {
    id: '25',
    name: 'Kevin Allen',
    email: 'kevin.allen@example.com',
    phone: '+1 (555) 567-8903',
    department: 'Youth Ministry',
  },
  {
    id: '26',
    name: 'Rebecca Young',
    email: 'rebecca.young@example.com',
    phone: '+1 (555) 678-9014',
    department: 'Youth Ministry',
  },
  {
    id: '27',
    name: 'Justin Hernandez',
    email: 'justin.hernandez@example.com',
    phone: '+1 (555) 789-0125',
    department: 'Youth Ministry',
  },
  {
    id: '28',
    name: 'Lauren King',
    email: 'lauren.king@example.com',
    phone: '+1 (555) 890-1236',
    department: 'Youth Ministry',
  },
  {
    id: '29',
    name: 'Brandon Wright',
    email: 'brandon.wright@example.com',
    phone: '+1 (555) 901-2347',
    department: 'Youth Ministry',
  },
  {
    id: '30',
    name: 'Megan Lopez',
    email: 'megan.lopez@example.com',
    phone: '+1 (555) 012-3458',
    department: 'Youth Ministry',
  },
  {
    id: '31',
    name: 'Tyler Hill',
    email: 'tyler.hill@example.com',
    phone: '+1 (555) 123-4570',
    department: 'Youth Ministry',
  },
  {
    id: '32',
    name: 'Kayla Scott',
    email: 'kayla.scott@example.com',
    phone: '+1 (555) 234-5681',
    department: 'Youth Ministry',
  },
  {
    id: '33',
    name: 'Jacob Green',
    email: 'jacob.green@example.com',
    phone: '+1 (555) 345-6782',
    department: 'Youth Ministry',
  },
  {
    id: '34',
    name: 'Samantha Adams',
    email: 'samantha.adams@example.com',
    phone: '+1 (555) 456-7893',
    department: 'Youth Ministry',
  },
  {
    id: '35',
    name: 'Zachary Baker',
    email: 'zachary.baker@example.com',
    phone: '+1 (555) 567-8904',
    department: 'Youth Ministry',
  },
];

export const mockRecentMessages: Message[] = [
  {
    id: '1',
    title: 'Youth Camp Reminder',
    content: "Don't forget about the youth camp this weekend!",
    type: 'email',
    recipientCount: 35,
    recipientIds: mockMembers.map((m) => m.id),
    status: 'delivered',
    sentAt: new Date('2024-08-15T10:30:00'),
  },
  {
    id: '2',
    title: 'Youth Camp Reminder',
    content: "Don't forget about the youth camp this weekend!",
    type: 'sms',
    recipientCount: 35,
    recipientIds: mockMembers.map((m) => m.id),
    status: 'delivered',
    sentAt: new Date('2024-08-15T10:30:00'),
  },
  {
    id: '3',
    title: 'Weekly Meeting Notice',
    content: 'Our weekly meeting is scheduled for Thursday at 7 PM.',
    type: 'email',
    recipientCount: 35,
    recipientIds: mockMembers.map((m) => m.id),
    status: 'delivered',
    sentAt: new Date('2024-08-14T09:00:00'),
  },
  {
    id: '4',
    title: 'Volunteer Opportunity',
    content: 'We need volunteers for the community outreach event next month.',
    type: 'email',
    recipientCount: 35,
    recipientIds: mockMembers.map((m) => m.id),
    status: 'delivered',
    sentAt: new Date('2024-08-13T14:20:00'),
  },
];
